# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    seed:
    - 0

algorithm:
  name: IFCA
  server:
    num_clusters: 10
    num_clients: null
    clients_sample_ratio: 0.3
    num_iters: 100
    log_dir: LCFL-test
    # tag: num_clusters_${{ matrix.num_clusters }}-seed_${{ matrix.seed }}
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: none
dataset:
  name: FedProxFEMNIST
  datadir: null  # default dir
model:
  name: cnn_femmist_tiny
seed: ${{ matrix.seed }}
