strategy:
  matrix:
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: IFCA
  server:
    num_clusters: 2
    num_clients: 200
    clients_sample_ratio: 0.1
    num_iters: 200
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: step  # StepLR
      step_size: 1
      gamma: 0.99
dataset:
  name: FedRotatedCIFAR10
  datadir: null  # default dir
  num_clusters: ${{ algorithm.server.num_clusters }}
  num_clients: ${{ algorithm.server.num_clients }}
  transform: null  # null for default dynamic transform (augmentation)
model:
  name: cnn_cifar
seed: ${{ matrix.seed }}
