strategy:
  matrix:
    num_clients:
    - 1200
    - 2400
    # - 4800
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: IFCA
  server:
    num_clusters: 4
    num_clients: ${{ matrix.num_clients }}
    clients_sample_ratio: 1.0
    num_iters: 60
    log_dir: LCFL-experiments
    tag: num_clusters_${{ matrix.num_clusters }}-seed_${{ matrix.seed }}
  client:
    lr: 0.02
    num_epochs: 10
    batch_size: null  # null for default batch size
    scheduler:
      name: none
dataset:
  name: FedRotatedMNIST
  datadir: null  # default dir
  num_rotations: ${{ algorithm.server.num_clusters }}
  num_clients: ${{ algorithm.server.num_clients }}
  transform: none  # none for static transform (only normalization, no augmentation)
model:
  name: cnn_femmist_tiny
seed: ${{ matrix.seed }}
