strategy:
  matrix:
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: LCFL
  server:
    num_clusters: 2
    num_clients: 200
    clients_sample_ratio: 1.0
    num_iters: 100
    num_warmup_iters: 5
    local_warmup: false
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: step
      step_size: 1
      gamma: 0.99
dataset:
  name: FedRotatedMNIST
  datadir: null  # default dir
  num_clusters: ${{ algorithm.server.num_clusters }}
  num_clients: ${{ algorithm.server.num_clients }}
  transform: none  # null for default dynamic transform (augmentation)
model:
  name: cnn_femmist_tiny
seed: ${{ matrix.seed }}
