strategy:
  matrix:
    dataset_transform:
    - null  # null for default dynamic transform (augmentation)
    - none  # none for static transform (only normalization, no augmentation)
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: LCFL
  server:
    num_clusters: 2
    num_clients: 200
    clients_sample_ratio: 0.1
    num_iters: 200
    num_warmup_iters: 5
    local_warmup: false
    warmup_clients_sample_ratio: 0.6
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: step  # StepLR
      step_size: 1
      gamma: 0.99
dataset:
  name: FedRotatedCIFAR10
  datadir: null  # default dir
  num_rotations: ${{ algorithm.server.num_clusters }}
  num_clients: ${{ algorithm.server.num_clients }}
  transform: ${{ matrix.dataset_transform }}
model:
  name: cnn_cifar_small
seed: ${{ matrix.seed }}
