# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    num_clusters:
    - 6
    - 2
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: LCFL
  server:
    num_clusters: ${{ matrix.num_clusters }}
    num_clients: null
    clients_sample_ratio: 0.4
    num_iters: 150
    num_warmup_iters: 10
    local_warmup: false
    warmup_clients_sample_ratio: 0.6
  client:
    lr: 0.1
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: step  # StepLR
      step_size: 1
      gamma: 0.99
dataset:
  name: FedShakespeare
  datadir: null  # default dir
model:
  name: rnn
seed: ${{ matrix.seed }}
