# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    num_clusters:
    - 10
    - 5
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4

algorithm:
  name: LCFL
  server:
    num_clusters: ${{ matrix.num_clusters }}
    num_clients: null
    clients_sample_ratio: 0.4
    num_iters: 150
    num_warmup_iters: 5
    local_warmup: false
    warmup_clients_sample_ratio: 0.6
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: none
dataset:
  name: FedProxFEMNIST
  datadir: /data2/wenhao/jupyter-data/FL/fedprox-femnist/
model:
  name: cnn_femmist_tiny
seed: ${{ matrix.seed }}
