# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    seed:
    - 0

algorithm:
  name: LCFL
  server:
    num_clusters: 4
    num_clients: null
    clients_sample_ratio: 1
    num_iters: 200
    num_warmup_iters: 10
    local_warmup: false
    warmup_clients_sample_ratio: 1
  client:
    lr: 0.06
    num_epochs: 20
    batch_size: null  # null for default batch size
    scheduler:
      name: step  # StepLR
      step_size: 1
      gamma: 0.995
dataset:
  name: FedShakespeare
  datadir: null  # default dir
model:
  name: rnn
seed: ${{ matrix.seed }}
