# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    seed:
    - 0

algorithm:
  name: LCFL
  server:
    num_clusters: 10
    num_clients: null
    clients_sample_ratio: 0.3
    num_iters: 100
    num_warmup_iters: 5
    local_warmup: false
    warmup_clients_sample_ratio: 0.6
    visiable_gpus:
    # - 0  # 0 occupied
    - 1
  client:
    lr: 0.03
    num_epochs: 5
    batch_size: null  # null for default batch size
    scheduler:
      name: none
dataset:
  name: FedProxFEMNIST
  datadir: /data2/wenhao/jupyter-data/FL/fedprox-femnist/
model:
  name: cnn_femmist_tiny
seed: ${{ matrix.seed }}
