# Test single run, so set each item in strategy.matrix to have only one value.

strategy:
  matrix:
    seed:
    - 0

algorithm:
  name: FedAvg
  server:
    num_clusters: 4
    num_clients: null
    clients_sample_ratio: 0.4
    num_iters: 150
  client:
    lr: 0.1
    num_epochs: 10
    batch_size: null  # null for default batch size
    scheduler:
      name: step  # StepLR
      step_size: 1
      gamma: 0.99
dataset:
  name: FedShakespeare
  datadir: null  # default dir
model:
  name: rnn
seed: ${{ matrix.seed }}
